apiVersion: batch/v1
kind: Job
metadata:
  name: finetune-job-1765401682
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: trainer-sa
      
      volumes:
      - name: data-volume
        emptyDir: {}
      - name: dshm
        emptyDir:
          medium: Memory

      initContainers:
      - name: data-loader
        image: google/cloud-sdk:alpine
        command:
        - "sh"
        - "-c"
        - "echo 'Downloading data...' && gsutil cp gs://e2ellm/staging/job-1765401682/dataset.jsonl /data/dataset.jsonl"
        volumeMounts:
        - name: data-volume
          mountPath: /data

      containers:
      - name: trainer
        image: gcr.io/stone-arch-474701-u5/finetuner:cpu-latest
        imagePullPolicy: Always
        command: ["python", "src/main.py"]
        args:
        - "--gcp_project"
        - "stone-arch-474701-u5"
        - "--gcp_bucket"
        - "e2ellm"
        - "--data_path"
        - "/data/dataset.jsonl"
        - "--model_name"
        - "Qwen/Qwen2.5-0.5B-Instruct"
        resources:
          requests:
            cpu: "2"
            memory: "16Gi"
            ephemeral-storage: "2Gi"
          limits:
            cpu: "4"
            memory: "32Gi"
            ephemeral-storage: "4Gi"
        volumeMounts:
        - name: data-volume
          mountPath: /data
        - name: dshm
          mountPath: /dev/shm
